{
 "title": "Kyuubi",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "baseFilter",
    "label": "baseFilter",
    "query": "job=~\"kyuubi\""
   },
   { "name": "baseLegend", "label": "baseLegend", "query": "{{instance}}" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kyuubi_jvm_uptime, instance)"
    }
   },
   {
    "name": "connType",
    "label": "connType",
    "query": "thrift_binary_connection,rest_connection,thrift_http_connection,metadata_request"
   },
   {
    "name": "opType",
    "label": "opType",
    "query": "ExecuteStatement,BatchJobSubmission,LaunchEngine"
   },
   { "name": "trendInterval", "label": "trendInterval", "query": "1m,5m,15m,30m,1h,3h,6h,12h,24h" }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kyuubi_jvm_uptime{$baseFilter})",
     "legendFormat": "${baseLegend}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kyuubi_jvm_uptime{$baseFilter,instance=~\"$instance\"}",
     "legendFormat": "${baseLegend}"
    }
   ]
  },
  {
   "title": "KeyStore Expiration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(kyuubi_thrift_ssl_cert_expiration{$baseFilter,instance=~\"$instance\"})",
     "legendFormat": "${baseLegend}"
    }
   ]
  },
  {
   "title": "Connection Opened",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(kyuubi_connection_opened_INTERACTIVE{$baseFilter,instance=~\"$instance\"})",
     "legendFormat": "total-interactive"
    },
    {
     "expr": "sum(kyuubi_connection_opened_BATCH{$baseFilter,instance=~\"$instance\"})",
     "legendFormat": "total-batch"
    },
    {
     "expr": "kyuubi_connection_opened_INTERACTIVE{$baseFilter,instance=~\"$instance\"}",
     "legendFormat": "${baseLegend}-interactive"
    },
    {
     "expr": "kyuubi_connection_opened_BATCH{$baseFilter,instance=~\"$instance\"}",
     "legendFormat": "${baseLegend}-batch"
    }
   ]
  },
  {
   "title": "Engine Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "kyuubi_engine_total{$baseFilter,instance=~\"$instance\"}",
     "legendFormat": "${baseLegend}"
    }
   ]
  },
  {
   "title": "Exec Pool Threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": " kyuubi_exec_pool_threads_alive{$baseFilter,instance=~\"$instance\"}",
     "legendFormat": "${baseLegend}-alive"
    },
    {
     "expr": " kyuubi_exec_pool_threads_active{$baseFilter,instance=~\"$instance\"}",
     "legendFormat": "${baseLegend}-active"
    },
    {
     "expr": " kyuubi_exec_pool_threads_queue{$baseFilter,instance=~\"$instance\"}",
     "legendFormat": "${baseLegend}-queue"
    }
   ]
  },
  {
   "title": "Engine Launching",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": " kyuubi_operation_state_LaunchEngine_running_total{$baseFilter,instance=~\"$instance\"}",
     "legendFormat": "${baseLegend}-interactive"
    },
    {
     "expr": " kyuubi_operation_state_BatchJobSubmission_pending_total{$baseFilter,instance=~\"$instance\"}",
     "legendFormat": "${baseLegend}-batch"
    }
   ]
  },
  {
   "title": "Max Batch Pending Elapse",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": " kyuubi_operation_batch_pending_max_elapse{$baseFilter,instance=~\"$instance\"}",
     "legendFormat": "${baseLegend}"
    }
   ]
  },
  {
   "title": "Session(new)[$trendInterval]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " increase(kyuubi_connection_total_INTERACTIVE{$baseFilter,instance=~\"$instance\"}[$trendInterval])",
     "legendFormat": "${baseLegend}-interactive"
    },
    {
     "expr": " increase(kyuubi_connection_total_BATCH{$baseFilter,instance=~\"$instance\"}[$trendInterval])",
     "legendFormat": "${baseLegend}-batch"
    }
   ]
  },
  {
   "title": "Operation(new)[$trendInterval]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " increase(kyuubi_operation_total_ExecuteStatement{$baseFilter,instance=~\"$instance\"}[$trendInterval])",
     "legendFormat": "${baseLegend}-interactive"
    },
    {
     "expr": " increase(kyuubi_operation_total_BatchJobSubmission{$baseFilter,instance=~\"$instance\"}[$trendInterval])",
     "legendFormat": "${baseLegend}-batch"
    }
   ]
  },
  {
   "title": "Fetch Rows[$trendInterval]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " increase(kyuubi_backend_service_fetch_result_rows_rate_total{$baseFilter,instance=~\"$instance\"}[$trendInterval])",
     "legendFormat": "${baseLegend}-result"
    },
    {
     "expr": " increase(kyuubi_backend_service_fetch_log_rows_rate_total{$baseFilter,instance=~\"$instance\"}[$trendInterval])",
     "legendFormat": "${baseLegend}-log"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "repeat": "memarea",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": " kyuubi_memory_usage_total_used{$baseFilter,instance=~\"$instance\"}",
     "legendFormat": "${baseLegend}"
    }
   ]
  },
  {
   "title": "JVM Memory Usage(Ratio)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": " kyuubi_memory_usage_total_used/kyuubi_memory_usage_heap_max{$baseFilter,instance=~\"$instance\"}",
     "legendFormat": "${baseLegend}"
    }
   ]
  },
  {
   "title": "JVM GC Count[$trendInterval]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(kyuubi_gc_ZGC_Cycles_count{$baseFilter,instance=~\"$instance\"}[$trendInterval])",
     "legendFormat": "${baseLegend}"
    },
    {
     "expr": "increase(kyuubi_gc_PS_MarkSweep_count{$baseFilter,instance=~\"$instance\"}[$trendInterval])",
     "legendFormat": "${baseLegend}"
    }
   ]
  },
  { "title": "Connection($connType)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }, "repeat": "connType" },
  {
   "title": "$connType(opened)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kyuubi_${connType}_opened{$baseFilter,instance=~\"$instance\"}",
     "legendFormat": "$baseLegend"
    }
   ]
  },
  {
   "title": "$connType(new)[$trendInterval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(kyuubi_${connType}_opened{$baseFilter,instance=~\"$instance\"}[$trendInterval])",
     "legendFormat": "$baseLegend"
    }
   ]
  },
  {
   "title": "$connType(total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kyuubi_${connType}_total{$baseFilter,instance=~\"$instance\"}",
     "legendFormat": "$baseLegend"
    },
    {
     "expr": "kyuubi_${connType}_total_total{$baseFilter,instance=~\"$instance\"}",
     "legendFormat": "$baseLegend"
    }
   ]
  },
  {
   "title": "$connType(failed)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kyuubi_${connType}_failed{$baseFilter,instance=~\"$instance\"}",
     "legendFormat": "$baseLegend"
    },
    {
     "expr": "kyuubi_${connType}_failed_total{$baseFilter,instance=~\"$instance\"}",
     "legendFormat": "$baseLegend"
    }
   ]
  },
  { "title": "Operation($opType)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 }, "repeat": "opType" },
  {
   "title": "$opType(pending/running)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kyuubi_operation_state_${opType}_pending_total{$baseFilter,instance=~\"$instance\"}",
     "legendFormat": "$baseLegend-pending"
    },
    {
     "expr": "kyuubi_operation_state_${opType}_running_total{$baseFilter,instance=~\"$instance\"}",
     "legendFormat": "$baseLegend-running"
    }
   ]
  },
  {
   "title": "$opType(new)[$trendInterval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(kyuubi_operation_total_${opType}{$baseFilter,instance=~\"$instance\"}[$trendInterval])",
     "legendFormat": "$baseLegend"
    }
   ]
  },
  {
   "title": "$opType(error)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kyuubi_operation_state_${opType}_error_total{$baseFilter,instance=~\"$instance\"}",
     "legendFormat": "$baseLegend"
    }
   ]
  },
  {
   "title": "$opType(closed/finished)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kyuubi_operation_state_${opType}_closed_total{$baseFilter,instance=~\"$instance\"}",
     "legendFormat": "$baseLegend-closed"
    },
    {
     "expr": "kyuubi_operation_state_${opType}_finished_total{$baseFilter,instance=~\"$instance\"}",
     "legendFormat": "$baseLegend-finished"
    }
   ]
  },
  { "title": "Extra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Metadata Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "kyuubi_metadata_request_opened{$baseFilter,instance=~\"$instance\"}",
     "legendFormat": "${baseLegend} Opened"
    },
    {
     "expr": "kyuubi_metadata_request_total_total{$baseFilter,instance=~\"$instance\"}",
     "legendFormat": "${baseLegend} Total"
    },
    {
     "expr": "kyuubi_metadata_request_failed_total{$baseFilter,instance=~\"$instance\"}",
     "legendFormat": "${baseLegend} Failed"
    },
    {
     "expr": "kyuubi_metadata_request_retrying_total{$baseFilter,instance=~\"$instance\"}",
     "legendFormat": "${baseLegend} Retring"
    }
   ]
  },
  {
   "title": "Metadata Request(new)[$trendInterval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "increase(kyuubi_metadata_request_total_total{$baseFilter,instance=~\"$instance\"}[$trendInterval])",
     "legendFormat": "${baseLegend}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "kyuubi_thread_state_runnable_count{$baseFilter,instance=~\"$instance\"}",
     "legendFormat": "${baseLegend} Runnable"
    },
    {
     "expr": "kyuubi_thread_state_blocked_count{$baseFilter,instance=~\"$instance\"}",
     "legendFormat": "${baseLegend} Blocked"
    },
    {
     "expr": "kyuubi_thread_state_waiting_count{$baseFilter,instance=~\"$instance\"}",
     "legendFormat": "${baseLegend} Waiting"
    }
   ]
  },
  {
   "title": "JVM Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "Eden Space",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kyuubi_memory_usage_pools_PS_Eden_Space_used{$baseFilter,instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Eden Space Used"
      },
      {
       "expr": "kyuubi_memory_usage_pools_Par_Eden_Space_committed{$baseFilter,instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Eden Space Committed"
      },
      {
       "expr": "kyuubi_memory_usage_pools_Par_Eden_Space_max{$baseFilter,instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Eden Space Max"
      }
     ]
    },
    {
     "title": "Old Gen",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kyuubi_memory_usage_pools_PS_Old_Gen_used{$baseFilter,instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Old Gen Used"
      },
      {
       "expr": "kyuubi_memory_usage_pools_CMS_Old_Gen_committed{$baseFilter,instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Old Gen Committed"
      },
      {
       "expr": "kyuubi_memory_usage_pools_CMS_Old_Gen_max{$baseFilter,instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Old Gen Max"
      }
     ]
    },
    {
     "title": "Survivor Space",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kyuubi_memory_usage_pools_PS_Survivor_Space_used{$baseFilter,instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Survivor Space Used"
      },
      {
       "expr": "kyuubi_memory_usage_pools_Par_Survivor_Space_committed{$baseFilter,instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Survivor Space Committed"
      },
      {
       "expr": "kyuubi_memory_usage_pools_Par_Survivor_Space_max{$baseFilter,instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Survivor Space Max"
      }
     ]
    },
    {
     "title": "Metaspace",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kyuubi_memory_usage_pools_Metaspace_used{$baseFilter,instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Metaspace Used"
      },
      {
       "expr": "kyuubi_memory_usage_pools_Metaspace_committed{$baseFilter,instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Metaspace Committed"
      },
      {
       "expr": "kyuubi_memory_usage_pools_Metaspace_max{$baseFilter,instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Metaspace Max"
      }
     ]
    },
    {
     "title": "Compressed Class",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kyuubi_memory_usage_pools_Compressed_Class_Space_used{$baseFilter,instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Compressed Class Used"
      },
      {
       "expr": "kyuubi_memory_usage_pools_Compressed_Class_Space_committed{$baseFilter,instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Compressed Class Committed"
      },
      {
       "expr": "kyuubi_memory_usage_pools_Compressed_Class_Space_max{$baseFilter,instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Compressed Class Max"
      }
     ]
    },
    {
     "title": "Code Cache",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kyuubi_memory_usage_pools_Code_Cache_used{$baseFilter,instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Code Cache Used"
      },
      {
       "expr": "kyuubi_memory_usage_pools_Code_Cache_committed{$baseFilter,instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Code Cache Committed"
      },
      {
       "expr": "kyuubi_memory_usage_pools_Code_Cache_max{$baseFilter,instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Code Cache Max"
      }
     ]
    }
   ]
  }
 ]
}