#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Style

on:
  pull_request:
    branches:
      - master
      - branch-*

concurrency:
  group: linter-${{ github.ref }}
  cancel-in-progress: true

# no install runs before style check because it is expensive, we can skip build if style fails
# Well, sometimes when we introduce a new module, it may 'fail' the style check for missing
# dependency we just create for other module to inherit.
# We can ignore this failure and merge the PR, if we see the style check pass on the new module
# or via a local quick verification.
jobs:
  linter:
    name: Style check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 8
          cache: 'maven'
          check-latest: false
      - name: Scalastyle with maven
        run: build/mvn scalastyle:check -Pflink-provided,hive-provided,spark-provided,spark-block-cleaner,spark-3.3,spark-3.2,spark-3.1,tpcds
      - name: Print scalastyle error report
        if: failure()
        run: >-
          for log in `find * -name "scalastyle-output.xml"`;
            do
              if grep -q "error" $log; then
                cat $log;
              fi
          done
      - name: JavaStyle with maven
        run: build/mvn spotless:check -Pflink-provided,hive-provided,spark-provided,spark-block-cleaner,spark-3.3,spark-3.2,spark-3.1,tpcds
      - name: setup npm
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Web UI Style with node
        run: |
          cd ./kyuubi-server/web-ui
          npm install pnpm -g
          pnpm install
          pnpm run lint
          echo "---------------------------------------Notice------------------------------------"
          echo "If this style check fail, you should follow these commands for a tentative fix"
          echo "* cd ./kyuubi-server/web-ui"
          echo "* npm run lint-fix"
          echo "Following the above steps can solve many style problems. "
          echo "If there is a problem that cannot be fixed by the command, "
          echo "you need to manually fix it by following the information told by the command above"
          echo "---------------------------------------------------------------------------------"
